version: '3.6'

volumes:
  photoshow_config:
    name: photoshow_config
  photoshow_thumbs:
    name: photoshow_thumbs

services:
  photoshow:
    #env_file: .env
    environment:
# Uncomment for nginx proxy
#      VIRTUAL_HOST: ${PHOTOSHOW_VIRTUAL_HOST}
#      NETWORK_ACCESS: internal

      TZ: ${TIMEZONE}
      PUID: 1000
      PGID: 1000
    volumes:
      - photoshow_config:/config
      - /media/photoshow:/Pictures
      - photoshow_thumbs:/Thumbs
#    restart: unless-stopped

# Uncomment for nginx proxy
#    networks:
#      proxy_net:
#        aliases:
#          - photos
    ports:
      - "8910:80"

    image: linuxserver/photoshow:latest
#    build:
#      context: .
#      dockerfile: Dockerfile.photoshow

# Uncomment for nginx proxy
#networks:
#  proxy_net:
#    name: proxy_net
#    external: true


